services:
  dbt:
    build:
      context: ../../../etl/dbt/
      dockerfile: Dockerfile.dbt 
    image: dbt-render-db:latest
    container_name: dbt-render-db
    environment:
      - DBT_HOST=${DBT_HOST}
      - DBT_USER=${DBT_USER}
      - DBT_PASSWORD=${DBT_PASSWORD}
      - DBT_DBNAME=${DBT_DBNAME}
      - DBT_PORT=${DBT_PORT}
      - DBT_SCHEMA=${DBT_SCHEMA}