version: 2

sources:
  - name: clinic
    schema: clinic
    tables:
      - name: appointments
      - name: professionals
      - name: services
      - name: specialties

  - name: marketing
    schema: marketing
    tables:
      - name: marketing_benchmarks
      - name: marketing_search_terms

  - name: operations
    schema: operations
    tables:
      - name: professional_contracts

  - name: staging
    schema: staging
    tables:
      - name: stg_google_trends