flowchart LR
    User[Usuario Empresarial]
    Browser[Web App React]
    BFF[BFF Spring Boot]

    ReservaSvc[Reservas Service]
    PagamentoSvc[Pagamentos Service]
    AnalyticsSvc[Analytics Service]

    ReservaDB[(Postgres Reservas)]
    PagamentoDB[(Postgres Pagamentos)]
    AnalyticsDB[(Postgres Analytics)]

    Redis[(Redis Cache and Event Buffer)]
    Jobs["Analytics Jobs\nBatch Scheduler"]

    User --> Browser
    Browser --> BFF

    BFF --> ReservaSvc
    BFF --> PagamentoSvc
    BFF --> AnalyticsSvc

    ReservaSvc --> ReservaDB
    PagamentoSvc --> PagamentoDB
    AnalyticsSvc --> AnalyticsDB

    ReservaSvc --> Redis
    PagamentoSvc --> Redis

    Redis --> Jobs
    Jobs --> AnalyticsDB
